version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seller-platform-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_USER=postgres
      - DB_HOST=postgis
      - DB_NAME=seller-platform-db
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PORT=3000
    command: sh -c "npm run start"
    depends_on:
      - db
volumes:
  pgdata:
